apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: online-shop

spec:
  replicas: 3

  # strategy:
  #   blueGreen:
  #     activeService: shop-active
  #     previewService: shop-preview
  #     autoPromotionEnabled: true
  #     scaleDownDelaySeconds: 60

  strategy:
   canary:
    steps:
      - setWeight: 20
      - pause: {}

      - setWeight: 50
      - pause: {}

      - setWeight: 100

  selector:
    matchLabels:
      app: online-shop

  template:
    metadata:
      labels:
        app: online-shop

    spec:
      imagePullSecrets:
        - name: regcred

      containers:
      - name: shop
        image: 501673236830.dkr.ecr.us-west-2.amazonaws.com/demo-private/ui:eea72f07af37e1ac6c4d6fec3d8714110314b4a9
        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10