apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: online-shop
  annotations:
    argocd-image-updater.argoproj.io/image-list: cart=626072240565.dkr.ecr.us-west-2.amazonaws.com/retail-store-cart
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  replicas: 3

  strategy:
    blueGreen:
      activeService: shop-active
      previewService: shop-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 60

  selector:
    matchLabels:
      app: online-shop

  template:
    metadata:
      labels:
        app: online-shop

    spec:
      # ✅ FIX: ECR authentication added
      imagePullSecrets:
        - name: regcred

      containers:
      - name: shop
        image: 626072240565.dkr.ecr.us-west-2.amazonaws.com/retail-store-cart
        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10