apiVersion: v1
kind: Service
metadata:
  name: shop-active
spec:
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: shop-preview
spec:
  ports:
  - port: 80
    targetPort: 3000